### ISSUE TITLE
Need to add moment to package.json

### ISSUE THREAD

**Issue by ericmaxwell2003** [realm-demos/EventBlank#3]
When you run the install instructions for the server.  When you get to the instruction on loading test data via the `test-data.js` script, if you just run `npm install`, you get an error stating that the `moment module` could not be found.   The work around is to install this module manually, but would be nice to add this to the `package.json`.

**Example**
```
Erics-MBP:server ericmaxwell$ npm install
EventBlankCli@1.0.0 /Users/ericmaxwell/Projects/cms/EventBlank/server
├─┬ async@2.5.0 
│ └── lodash@4.17.4 
├─┬ fs-extra@4.0.2 
│ ├── jsonfile@4.0.0 
│ └── universalify@0.1.1 
├─┬ optimist@0.6.1 
│ └── wordwrap@0.0.3 
└── uuid@3.1.0 

npm WARN EventBlankCli@1.0.0 No repository field.
Erics-MBP:server ericmaxwell$ node test-data.js --host localhost --port 9080 --username eventblank-admin@host --password password --delete yes --amount plenty
Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ericmaxwell/Projects/cms/EventBlank/server/entities/session.js:1:78)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Erics-MBP:server ericmaxwell$ npm install moment
EventBlankCli@1.0.0 /Users/ericmaxwell/Projects/cms/EventBlank/server
└── moment@2.18.1 

npm WARN EventBlankCli@1.0.0 No repository field.
Erics-MBP:server ericmaxwell$ node test-data.js --host localhost --port 9080 --username eventblank-admin@host --password password --delete yes --amount plenty
[app] Creating test data...
[app] Connected.
[app] Opened realm file
[app] Completed.
Erics-MBP:server ericmaxwell$ 
```

**Comment by icanzilb** [comment]
Fixed via https://github.com/realm-demos/EventBlank/pull/4
